baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Heather Loomis Photography'
theme = 'original'
copyright = 'Heather Loomis'

[[params.social]]
	site = 'facebook'
	url = 'https://facebook.com/HeatherLoomisPhotography'
[[params.social]]
	site = 'instagram'
	url = 'https://instagram.com/HeatherLoomisPhoto'
[[params.social]]
	site = 'github'
	url = 'https://github.com/heatherloomis'

[imaging.exif]
includeFields = "Keywords"
